# Generated by Django 4.1.5 on 2023-03-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_useraccount_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='addrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Restaurant_Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Auth_Person', models.CharField(max_length=50)),
                ('Auth_Email', models.CharField(max_length=50)),
                ('Auth_Phone', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
