# Generated by Django 4.1.5 on 2023-03-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_addrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='userType',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
