# Generated by Django 4.1.5 on 2023-03-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_useraccount_usertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addrest',
        ),
    ]
