# Generated by Django 4.1.5 on 2023-03-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_addrest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='useraccount',
        ),
    ]
