# Generated by Django 4.1.5 on 2023-03-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_delete_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='useraccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Image', models.CharField(max_length=500)),
                ('Adress', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('userType', models.CharField(max_length=20)),
            ],
        ),
    ]
