# Generated by Django 4.1.5 on 2023-03-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_addrest_first_name_addrest_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='addrest',
            name='last_name',
        ),
    ]
