# Generated by Django 4.1.5 on 2023-03-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_addrest_email_addrest_restaurant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Restaurant_Image', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
            ],
        ),
    ]
