# Generated by Django 4.1.5 on 2023-03-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_addmenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addfood',
        ),
    ]
