# Generated by Django 4.1.5 on 2023-03-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_delete_addfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='addfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_Name', models.CharField(max_length=50)),
                ('Menu_Name', models.CharField(max_length=50)),
                ('Menu_Item', models.CharField(max_length=50)),
                ('Image', models.CharField(max_length=500)),
                ('Quantity', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Cooking_Time', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
    ]
