# Generated by Django 4.1.5 on 2023-03-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_addfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='addoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_Name', models.CharField(max_length=50)),
                ('Menu_Item', models.CharField(max_length=50)),
                ('offer', models.CharField(max_length=50)),
                ('Start_Date', models.CharField(max_length=50)),
                ('End_Date', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
    ]
