# Generated by Django 4.1.5 on 2023-03-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_addoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='addfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_Name', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Feedback', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
            ],
        ),
    ]
